# Numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([3, 6, 32, 7])

In [3]:
myarr

array([ 3,  6, 32,  7])

# Aray creation: conversion from other Python structures

In [5]:
lisarray = np.array([[1, 2, 3], [5, 8, 5], [0, 3, 1]])

In [6]:
lisarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [8]:
np.array({32, 45, 32})

array({32, 45}, dtype=object)

In [9]:
zeros = np.zeros((2,5))

In [10]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
rng = np.arange(15)

In [15]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
lspace = np.linspace(1, 5, 12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [17]:
emp = np.empty((4,6))
emp

array([[6.95296896e-310, 6.95296895e-310, 0.00000000e+000,
        0.00000000e+000, 9.71118682e-312, 4.94065646e-324],
       [0.00000000e+000, 0.00000000e+000, 4.04738577e-320,
        0.00000000e+000, 1.23022346e-321, 9.71154060e-312],
       [1.78022342e-306, 1.05700345e-307, 0.00000000e+000,
        9.71154074e-312, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 4.54540394e-322, 1.29060531e-306,
        2.13620807e-306, 1.69118787e-306,             nan]])

In [24]:
emp_like = np.empty_like(lspace)
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [25]:
ide = np.identity(6)
ide

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [26]:
ide.shape

(6, 6)

In [29]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
arr = arr.reshape(3, 33)

In [34]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [36]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [38]:
arr = arr.ravel()

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
x = [[1, 2, 3], [5, 8, 5], [0, 3, 1]]

In [41]:
ar = np.array(x)

In [42]:
ar

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [45]:
ar.sum(axis=0)

array([ 6, 13,  9])

In [46]:
ar.sum(axis=1)

array([ 6, 18,  4])

In [47]:
ar.T

array([[1, 5, 0],
       [2, 8, 3],
       [3, 5, 1]])

In [49]:
ar.flat

In [52]:
for item in ar.flat:
    print(item)

1
2
3
5
8
5
0
3
1


In [54]:
one = np.array([1, 3, 4, 686, 5])

In [55]:
one.argmax()

3

In [56]:
one.argmin()

0

In [58]:
one.argsort()

array([0, 1, 2, 4, 3], dtype=int64)

In [59]:
ar

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [60]:
ar.argsort()

array([[0, 1, 2],
       [0, 2, 1],
       [0, 2, 1]], dtype=int64)

In [61]:
ar.argmin()

6

In [62]:
ar.argmax()

4

In [63]:
ar.argmax(axis = 0)

array([1, 1, 1], dtype=int64)

In [64]:
ar.argmax(axis = 1)

array([2, 1, 1], dtype=int64)

In [65]:
ar.ravel()

array([1, 2, 3, 5, 8, 5, 0, 3, 1])

In [66]:
ar.reshape(1,9)

array([[1, 2, 3, 5, 8, 5, 0, 3, 1]])

In [67]:
ar

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [71]:
ar2 = np.array([[2, 5, 7], [3, 7, 5], [8, 66, 44]])

In [73]:
ar2

array([[ 2,  5,  7],
       [ 3,  7,  5],
       [ 8, 66, 44]])

In [74]:
ar +ar2

array([[ 3,  7, 10],
       [ 8, 15, 10],
       [ 8, 69, 45]])

In [75]:
[2, 66] + [7, 4]

[2, 66, 7, 4]

In [76]:
ar

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [77]:
ar2

array([[ 2,  5,  7],
       [ 3,  7,  5],
       [ 8, 66, 44]])

In [78]:
ar*ar2

array([[  2,  10,  21],
       [ 15,  56,  25],
       [  0, 198,  44]])

In [79]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.23606798, 2.82842712, 2.23606798],
       [0.        , 1.73205081, 1.        ]])

In [80]:
ar.sum()

28

In [81]:
ar.max()

8

In [82]:
ar.min()

0

In [83]:
ar

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [88]:
np.where(ar>5)

(array([1], dtype=int64), array([1], dtype=int64))

In [89]:
type(np.where(ar>5))

tuple

In [91]:
np.count_nonzero(ar)

8

In [93]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 1, 2], dtype=int64))

In [94]:
import sys

In [95]:
py_ar = [0, 4, 55, 2]

In [104]:
np_ar = np.array(py_ar)
np_ar

array([ 0,  4, 55,  2])

In [105]:
sys.getsizeof(1) * len(py_ar)

112

In [107]:
np_ar.itemsize*np_ar.size

16